docs: fix build failure on docs.rs
Latest released didn't publish the doc on docs.rs because:

[INFO] [stderr] error[E0557]: feature has been removed
[INFO] [stderr]  --> src/lib.rs:2:29
[INFO] [stderr]   |
[INFO] [stderr] 2 | #![cfg_attr(docsrs, feature(doc_auto_cfg))]
[INFO] [stderr]   |                             ^^^^^^^^^^^^ feature has been removed
[INFO] [stderr]   |
[INFO] [stderr]   = note: removed in 1.92.0; see <https://github.com/rust-lang/rust/pull/138907> for more information
[INFO] [stderr]   = note: merged into `doc_cfg`